**JOB LAYOFF DATA (CLEANING)**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\projects\tech_layoffs_2026_tracker.csv")

In [3]:
df.head(2)

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"

In [4]:
df.shape

(28, 26)

In [5]:
df.columns

Index(['company', 'layoff_date', 'jobs_cut', 'pct_workforce_cut', 'sector',
       'country', 'hq_city', 'ai_cited', 'reason_stated',
       'company_revenue_2025_bn', 'pre_layoff_headcount',
       'stock_change_day_pct', 'simultaneous_ai_investment_bn',
       'roles_most_affected', 'replacement_roles', 'ceo_quote', 'layoffs_2024',
       'layoffs_2025', 'verified_source', 'month', 'quarter', 'region',
       'layoff_size_category', 'stock_reaction', 'laid_off_vs_headcount_pct',
       'data_as_of'],
      dtype='object')

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

company                          0
layoff_date                      0
jobs_cut                         0
pct_workforce_cut                0
sector                           0
country                          0
hq_city                          0
ai_cited                         0
reason_stated                    0
company_revenue_2025_bn          0
pre_layoff_headcount             0
stock_change_day_pct             0
simultaneous_ai_investment_bn    0
roles_most_affected              0
replacement_roles                0
ceo_quote                        0
layoffs_2024                     0
layoffs_2025                     0
verified_source                  0
month                            0
quarter                          0
region                           0
layoff_size_category             0
stock_reaction                   0
laid_off_vs_headcount_pct        0
data_as_of                       0
dtype: int64

In [8]:
df.describe()

,jobs_cut,pct_workforce_cut,company_revenue_2025_bn,pre_layoff_headcount,stock_change_day_pct,simultaneous_ai_investment_bn,layoffs_2024,layoffs_2025,laid_off_vs_headcount_pct
count,28.000000,28.000000,28.00000,2.800000e+01,28.000000,28.000000,28.000000,28.000000,28.000000
mean,3612.357143,10.639286,63.62500,1.076631e+05,0.832143,14.046429,944.642857,1951.785714,10.452143
std,6546.591373,10.433505,139.44986,2.915339e+05,1.742721,34.751824,1615.511574,3328.482085,10.719330
min,50.000000,0.100000,0.00000,2.500000e+03,-2.100000,0.000000,0.000000,0.000000,0.320000
25%,989.500000,2.525000,3.50000,8.750000e+03,-0.325000,0.000000,0.000000,0.000000,1.975000
50%,1000.000000,7.750000,9.40000,1.850000e+04,0.650000,0.450000,0.000000,500.000000,7.205000
75%,2050.000000,15.000000,53.90000,8.050000e+04,1.850000,2.250000,1125.000000,1812.500000,15.810000
max,30000.000000,40.000000,716.90000,1.550000e+06,5.800000,115.000000,6000.000000,14000.000000,40.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        28 non-null     object
 1   layoff_date                    28 non-null     object
 2   jobs_cut                       28 non-null     int64
 3   pct_workforce_cut              28 non-null     float64
 4   sector                         28 non-null     object
 5   country                        28 non-null     object
 6   hq_city                        28 non-null     object
 7   ai_cited                       28 non-null     bool
 8   reason_stated                  28 non-null     object
 9   company_revenue_2025_bn        28 non-null     float64
 10  pre_layoff_headcount           28 non-null     int64
 11  stock_change_day_pct           28 non-null     float64
 12  simultaneous_ai_investment_bn  28 non-null     float64
 13  roles_most_affected            28 non-null     object
 14  replacement_roles              28 non-null     object
 15  ceo_quote                      28 non-null     object
 16  layoffs_2024                   28 non-null     int64
 17  layoffs_2025                   28 non-null     int64
 18  verified_source                28 non-null     object
 19  month                          28 non-null     object
 20  quarter                        28 non-null     object
 21  region                         28 non-null     object
 22  layoff_size_category           28 non-null     object
 23  stock_reaction                 28 non-null     object
 24  laid_off_vs_headcount_pct      28 non-null     float64
 25  data_as_of                     28 non-null     object
dtypes: bool(1), float64(5), int64(4), object(16)
memory usage: 5.6+ KB

In [10]:
df['layoff_date'] = pd.to_datetime(df['layoff_date'])

In [12]:
df.to_csv("AI_job_layoff_data.csv",index=False)

In [14]:
###Q1-What is average workforce reduction
df['pct_workforce_cut'].mean()

10.639285714285714

In [21]:
###Q2-Which company has highest layoff
df.groupby('company')['jobs_cut'].sum().sort_values(ascending=False).head(1)

company
Oracle    30000
Name: jobs_cut, dtype: int64

In [22]:
###Q3-Which category is most affected
df.groupby('sector')['jobs_cut'].sum().sort_values(ascending=False).head(1)

sector
Enterprise Software    31600
Name: jobs_cut, dtype: int64

In [25]:
###Q4-What percentage of layoffs is contributed by each company?
total = df['jobs_cut'].sum()
df.groupby('company')['jobs_cut'].sum().apply(lambda x:(x/total)*100).sort_values(ascending=False).head(5)

company
Oracle                      29.660095
Amazon                      15.818717
Meta Platforms (Planned)    15.818717
Cisco                        5.932019
Telefonica                   4.943349
Name: jobs_cut, dtype: float64

In [38]:
###Q5-Which region is most affected by layoffs
df.groupby('region')['jobs_cut'].sum().sort_values(ascending=False).head(2)

region
North America    85046
Europe           11500
Name: jobs_cut, dtype: int64